name: Build and Deploy Hexo to gh-pages and cf-pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 22.20.0 (same as local)
        uses: actions/setup-node@v4
        with:
          node-version: 22.20.0

      - name: Install dependencies & build site (for GitHub Pages)
        run: |
          npm ci || npm install
          npx hexo clean
          npx hexo generate
        env:
          NODE_ENV: production

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          keep_files: false

      # ✨ 新增：为 Cloudflare Pages 生成并推送 cf-pages 分支
      - name: Build for Cloudflare Pages
        run: |
          npx hexo clean
          npx hexo generate --config _config.yml,config_cloudflare.yml

      - name: Deploy to cf-pages branch
        run: |
          cd public
          git init
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Deploy to cf-pages"
          git branch -M main
          git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" main:cf-pages
