name: Build and Deploy Hexo to gh-pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 22.20.0 (same as local)
        uses: actions/setup-node@v4
        with:
          node-version: 22.20.0

      - name: Install dependencies & build site
        run: |
          npm ci || npm install
          npx hexo clean
          npx hexo generate
        env:
          NODE_ENV: production

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          keep_files: false
